on:
  pull_request:
    branches: ["main"]
jobs:
  pull-request:
    name: 🎫 pull-request
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # This step is required
      - name: checkout source
        uses: actions/checkout@master
        with:
          fetch-depth: 2 # Fetch enough history to compare commits
      - name: Calculate Next Version
        uses: ./
        id: versioning
        with:
          is-draft: true # Publich as draft version
          build-metadata: ${{ github.workflow_sha }}
          create-tag: false # Don't create tag, only returns at output
          debug: true # Show debug messages
      - name: Show Output
        run: echo '${{ toJson(steps.versioning.outputs) }}'
